spring.application.name=medical-clinic-proxy
server.port=8081
medical-clinic.url=${MEDICAL_CLINIC_URL:http://localhost:8080}
spring.cloud.openfeign.circuitbreaker.enabled=true
logging.level.com.Czupson.medical_clinic_proxy=DEBUG
logging.level.feign=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
spring.cloud.openfeign.okhttp.enabled=true
springdoc.swagger-ui.enabled=true